name: scroll_pagination_flutter
description: "As the user scrolls down your screen, pages of things will slowly load and show."
version: 0.0.2
homepage: https://github.com/codeislife07/scroll_pagination_flutter

environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: ">=1.12.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  sliver_tools: ^0.2.12  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.0.9
  test: ^1.16.5

flutter:
